Fixed more code problems from QA testing.
I added a few `noqa` codes:

- Using a print statement to write to a StringIO is fine I think.

- Using the `@public` decorator instead of `declarePublic` is not
  possible with the PloneMessageFactory, which is not a function.
  So you get an AttributeError: 'MessageFactory' object has no attribute '__name__'